#Hosted online at https://hub.docker.com/r/henrinc/pfd_sfo_tools
FROM debian:bookworm-slim AS builder
WORKDIR /build

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    zlib1g-dev

RUN git clone https://github.com/bucanero/pfd_sfo_tools.git .

RUN cd /build/pfdtool/src && make
RUN cd /build/sfopatcher/src && make


FROM debian:bookworm-slim
COPY --from=builder /build/pfdtool/src/pfdtool /usr/local/bin/
COPY --from=builder /build/sfopatcher/src/sfopatcher /usr/local/bin/